### PR TITLE
Add codespell action

### PR DESCRIPTION
**Pull request by peternewman**
To catch future spelling mistakes

### CODE REVIEW

**Comment by peternewman** [comment]
This was generated by just following the steps in https://github.com/ssilverman/rdm-schema/pull/6#issuecomment-888359922

**Comment by peternewman** [comment]
Supersedes #1

**Comment by peternewman** [comment]
Bump @ssilverman , is this acceptable?

**Comment by ssilverman** [comment]
If it's been tested, I'll merge it. Just give a "yae" or "nay".

**Comment by peternewman** [comment]
Yes, see https://github.com/peternewman/rdm-schema/actions/runs/1112422783

As mentioned, this is just a rehash of https://github.com/ssilverman/rdm-schema/pull/10 so you don't have to press the squash button when merging.

**Comment by peternewman** [comment]
Thanks @ssilverman .

**Pull request merged**
