### PR TITLE
Add a default prefix power

### PR DESCRIPTION
**Pull request by peternewman**
Then you can always do value*prefixBase^prefixPower to get the actual value if you want regardless of which properties have been populated.

### CODE REVIEW

**Comment by ssilverman** [comment]
Note that "default", in JSON schemas, doesn't actually provide a default value. It's merely an annotation. i.e, if you retrieve, say "prefixBase", and the field is missing, it _won't_ return its default of 10. Same for this change. If "prefixPower" is missing, then its retrieval won't return zero (if its default is set to zero). (Maybe you know this detail, but I figured I'd explain for posterity, for any future viewers.)

Having said that, I'll approve this change so that it's consistent with "prefixBase" having a default.

**Review by ssilverman — APPROVED** [review]
Note that "default", in JSON schemas, doesn't actually provide a default value. It's merely an annotation. i.e, if you retrieve, say "prefixBase", and the field is missing, it won't return its default of 10. Same for this change. If "prefixPower" is missing, then its retrieval won't return zero (if its default is set to zero). (Maybe you know this detail, but I figured I'd explain for posterity, for any future viewers.)

Having said that, I'll approve this change so that it's consistent with "prefixBase" having a default.

**Comment by peternewman** [comment]
> Note that "default", in JSON schemas, doesn't actually provide a default value. It's merely an annotation. i.e, if you retrieve, say "prefixBase", and the field is missing, it won't return its default of 10. Same for this change. If "prefixPower" is missing, then its retrieval won't return zero (if its default is set to zero). (Maybe you know this detail, but I figured I'd explain for posterity, for any future viewers.)

I hadn't particularly gone looking at the detail, but surely the behaviour around any annotation like that is down to the library/wrapper you're using around it, for example this form clearly makes use of those defaults:
https://rjsf-team.github.io/react-jsonschema-form/

In a similar way to Python's `dict.get(key[, default])` I could imagine a library having the option to retrieve the default if there is no value set.

> Having said that, I'll approve this change so that it's consistent with "prefixBase" having a default.

Thanks. Are you happy to merge it too?

**Comment by ssilverman** [comment]
Yep, agree with you on the library wrapper. It’s just that “default” is a commonly misunderstood thing (and unexpected, at first glance), so I felt compelled to explain it. :-)

Happy to merge. Every group and company and organization has different policies on merging. My current work usually has the people who submitted the PR doing the merge, so that’s just been my habit.

**Comment by peternewman** [comment]
> Yep, agree with you on the library wrapper. It’s just that “default” is a commonly misunderstood thing (and unexpected, at first glance), so I felt compelled to explain it. :-)

Makes sense.

> Happy to merge. Every group and company and organization has different policies on merging. My current work usually has the people who submitted the PR doing the merge, so that’s just been my habit.

GitHub doesn't work like that by default, I need to have Triage or probably Write permissions to have the rights to actually merge stuff.

**Pull request merged**
