### PR TITLE
Fix the validation errors

### PR DESCRIPTION
**Pull request by peternewman**
So the JSON is actually valid!

See also my incoming public review docs

### CODE REVIEW

**Review by ssilverman — APPROVED** [review]
👍 Thanks for finding these.

**Review by ssilverman — CHANGES_REQUESTED** [review]
Actually, @peternewman could you combine the commits into a single commit and then force push?

**Comment by peternewman** [comment]
I could, or you could just use the Squash and Merge option, which is probably less effort all round:
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits

You might need to enable it first:
https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by peternewman** [comment]
Is the Squash and Merge option acceptable @ssilverman or do you want me to have a go from my end?

**Comment by ssilverman** [comment]
I'm familiar with squash merges, I just wanted to give you an opportunity to create your own commit message. I can do it, no worries.

**Comment by ssilverman** [comment]
See: https://github.com/ssilverman/rdm-schema/pull/6#issuecomment-888343344

**Pull request merged**
