### PR TITLE
Add a codespell action to keep it clean of future typos

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by ssilverman** [comment]
Sorry to have missed this PR. I didn't get an email notification for some reason. My preference is to do one PR per change. (I've already fixed the typo, thanks for finding that.)

**Comment by peternewman** [comment]
> Sorry to have missed this PR. I didn't get an email notification for some reason.

No worries.

> My preference is to do one PR per change.

Okay, do you want me to cherry-pick that commit out?

> (I've already fixed the typo, thanks for finding that.)

Perhaps you haven't pushed then, it's still there currently:
https://github.com/ssilverman/rdm-schema/blame/e61c61573f1b078dffb779d5c9b1a6aaa1947a48/CHANGELOG.md#L413

**Comment by ssilverman** [comment]
That’s correct, I haven’t pushed yet.

**Comment by peternewman** [comment]
This is now just a single change PR @ssilverman .

**Comment by peternewman** [comment]
Bump @ssilverman

**Comment by ssilverman** [comment]
Question: Will this action prevent a merge or just show some notification if there's a typo?

Also, could you squash this into a single commit?

**Comment by peternewman** [comment]
> Question: Will this action prevent a merge or just show some notification if there's a typo?

That depends how/whether you configure branch protection:
https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

If you do nothing, this will just add an annotation against any PRs, like so:
https://github.com/peternewman/rdm-schema/pull/7/files

As well as tick/cross status against commits:
https://github.com/peternewman/rdm-schema/pull/7/commits

But with branch protection you can, if you want, only allow either PRs (or pushes too) to be merged when there are no spelling errors, to keep the branch clean. I'd say this will be particularly important for the validation PRs #6 #8 and #9 so you don't end up with broken JSON being merged in future.

You can also add words to skip:
https://github.com/codespell-project/actions-codespell/#parameter-ignore_words_list

Or if necessary, files:
https://github.com/codespell-project/actions-codespell/#parameter-skip

> Also, could you squash this into a single commit?

See the discussion elsewhere...

> Only one file is changed, but there are 4 commits.

One added the action, one fixed the typo (which I think you'd already fixed but not pushed at the time) and the other two were resyncing to try and get that fix in).

**Comment by ssilverman** [comment]
I think I see why more commits are being added. When I refer to "combining commits", I'm thinking of "interactive rebasing" and literally combining commits, not merging them. For example, if there's a few commits that only result in one file, you can use interactive rebase with the "f" command:
> `# f, fixup <commit> = like "squash", but discard this commit's log message`

**Comment by ssilverman** [comment]
@peternewman Would you like to hop on a screen sharing call and we can get all your changes in together? I'd really like to get your fixes and additions in.

**Comment by peternewman** [comment]
> I think I see why more commits are being added. When I refer to "combining commits", I'm thinking of "interactive rebasing" and literally combining commits, not merging them. For example, if there's a few commits that only result in one file, you can use interactive rebase with the "f" command:
> 
> > `# f, fixup <commit> = like "squash", but discard this commit's log message`

See https://github.com/ssilverman/rdm-schema/pull/6#issuecomment-888359922 I'm pretty certain that will keep you happy! I think this is the web version of fix-up.

> @peternewman Would you like to hop on a screen sharing call and we can get all your changes in together? I'd really like to get your fixes and additions in.

Thanks for the offer, unfortunately now doesn't work too well for me, I'm not really free for something like that until in a weeks time.

**Comment by peternewman** [comment]
Hi @ssilverman ,

Is #10 acceptable for you to merge instead of this?

Otherwise I should be able to fit in a screen sharing call at some point over the next few weeks if you really feel we need one. Do you want to drop me an email with some dates that work for you (if you've still got my email)?

**Comment by peternewman** [comment]
Merged as a GitHub squash via #10.

**Pull request closed without merging**
